---
name: ✂️ Cancel runs
"on":
  pull_request:
    types:
      - closed

jobs:

  cancel-runs:
    uses: kdeldycke/repomatic/.github/workflows/cancel-runs.yaml@36523e5a56f287e814210042ca7b852147a95498 # v7.0.0
