---
name: 🧹 Lint
"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.gif"
      - "**/*.jpeg"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.svg"
      - "**/*.webp"
  pull_request:
    branches-ignore:
      - major-version-increment
      - minor-version-increment
      - prepare-release

jobs:

  lint:
    uses: kdeldycke/repomatic/.github/workflows/lint.yaml@36523e5a56f287e814210042ca7b852147a95498 # v7.0.0
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
      VIRUSTOTAL_API_KEY: ${{ secrets.VIRUSTOTAL_API_KEY }}
