# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: kdeldycke
          template: classic
          base: ""
          config_display: columns
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_ignored: member, forker, stargazer
          plugin_achievements_limit: 7
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_types: commit
